config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'
  resources :posts, except: :show
  resources :operators, except: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  include OperatorRecordable::Extension
end

app/models/operator.rb
class Operator < ApplicationRecord
  acts_as_paranoid
  record_operator_on :create, :update, :destroy

  validates :name, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_paranoid
  record_operator_on :create, :update, :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action { OperatorRecordable.operator = Operator.find(Operator.ids.sample) }
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index; end
end

app/controllers/operators_controller.rb
class OperatorsController < ApplicationController
  def index
    @operators = Operator.all.with_deleted.preload(:creator, :updater, :deleter)
  end
    
  def new
    @operator = Operator.new
  end

  def create
    Operator.create!(params.require(:operator).permit(:name))
    redirect_to action: :index
  end

  def edit
    @operator = Operator.find(params[:id])
  end

  def update
    Operator.find(params[:id]).update!(params.require(:operator).permit(:name))
    redirect_to action: :index
  end

  def destroy
    Operator.find(params[:id]).destroy!
    redirect_to action: :index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.with_deleted.preload(:creator, :updater, :deleter)
  end
    
  def new
    @post = Post.new
  end

  def create
    Post.create!(params.require(:post).permit(:title, :body))
    redirect_to action: :index
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    Post.find(params[:id]).update!(params.require(:post).permit(:title, :body))
    redirect_to action: :index
  end

  def destroy
    Post.find(params[:id]).destroy!
    redirect_to action: :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<ul>
  <li><%= link_to 'Posts', posts_path %></li>
  <li><%= link_to 'Operators', operators_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OperatorRecordableExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/operators/_form.html.erb
<style type="text/css">
<!--
form ul {
  margin-bottom: 20px;
}
form ul li {
  list-style: none;
  margin-top: 10px;
}
form ul li label {
  margin-right: 5px;
  width: 50px;
  float: left;
}
-->
</style>

<%= form_with model: operator, local: true do |f| %>
  <ul>
    <li>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </li>
    <li>
      <%= f.submit %>
    </li>
  </ul>
<% end %>

app/views/operators/edit.html.erb
<%= render 'form', operator: @operator %>

app/views/operators/index.html.erb
<%= link_to "New", action: :new %>
<% if @operators.present? %>
<table>
  <caption>Operators</caption>
  <thead>
    <tr>
      <th>id</th>
      <th>name</th>
      <th>creator</th>
      <th>updater</th>
      <th>deleter</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @operators.each do |operator| %>
    <tr>
      <td><%= link_to_if operator.deleted?.!, operator.id, action: :edit, id: operator.id %></td>
      <td><%= operator.name %></td>
      <td><%= operator.creator&.name %></td>
      <td><%= operator.updater&.name %></td>
      <td><%= operator.deleter&.name %></td>
      <td><%= button_to "Delete", { action: :destroy, id: operator.id }, { method: :delete, disabled: operator.deleted? } %></td>
    </tr>
    <% end %>
  </tbody>
</table
<% end %>

app/views/operators/new.html.erb
<%= render 'form', operator: @operator %>

app/views/posts/_form.html.erb
<style type="text/css">
<!--
form ul {
  margin-bottom: 20px;
}
form ul li {
  list-style: none;
  margin-top: 10px;
}
form ul li label {
  margin-right: 5px;
  width: 50px;
  float: left;
}
-->
</style>

<%= form_with model: post, local: true do |f| %>
  <ul>
    <li>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </li>
    <li>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </li>
    <li>
      <%= f.submit %>
    </li>
  </ul>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<%= link_to "New", action: :new %>
<% if @posts.present? %>
<table>
  <caption>Posts</caption>
  <thead>
    <tr>
      <th>id</th>
      <th>title</th>
      <th>body</th>
      <th>creator</th>
      <th>updater</th>
      <th>deleter</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
    <tr>
      <td><%= link_to_if post.deleted?.!, post.id, action: :edit, id: post.id %></td>
      <td><%= post.title %></td>
      <td><%= post.body %></td>
      <td><%= post.creator&.name %></td>
      <td><%= post.updater&.name %></td>
      <td><%= post.deleter&.name %></td>
      <td><%= button_to "Delete", { action: :destroy, id: post.id }, { method: :delete, disabled: post.deleted? } %></td>
    </tr>
    <% end %>
  </tbody>
</table
<% end %>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>